# Generated by Django 3.0.4 on 2020-03-27 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee', models.BooleanField(default=True, verbose_name='trainee')),
                ('count_code', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainee',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.BooleanField(default=True, verbose_name='trainer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TraineePhy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('age', models.IntegerField()),
                ('current_weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('goal_weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('health_condition', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Trainee')),
            ],
            options={
                'db_table': 'trainee_phy',
            },
        ),
        migrations.CreateModel(
            name='TraineeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.IntegerField()),
                ('street_no', models.IntegerField()),
                ('village', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('dist_city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Trainee')),
            ],
            options={
                'db_table': 'trainee_address',
            },
        ),
    ]
