# Generated by Django 2.2.10 on 2020-04-17 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("user", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="trainee",
            name="trainer_ass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.Trainer",
            ),
        )
    ]
