# Generated by Django 3.0.4 on 2020-03-27 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='dob',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
