# Generated by Django 3.0.4 on 2020-03-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200327_1548'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainer',
            table='trainer',
        ),
    ]
