# Generated by Django 3.0.4 on 2020-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0002_auto_20200417_2212")]

    operations = [
        migrations.AddField(
            model_name="trainee",
            name="age",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainee",
            name="current_weight",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainee",
            name="goal_weight",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainee",
            name="health_condition",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainee",
            name="height",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
