# Generated by Django 3.0.4 on 2020-03-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200327_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='trainer_ass',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Trainer'),
        ),
    ]
