# Generated by Django 3.0.4 on 2020-04-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("user", "0003_auto_20200423_1404")]

    operations = [
        migrations.AlterField(
            model_name="trainee",
            name="gender",
            field=models.CharField(blank=True, default="Male", max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="trainee",
            name="phone",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="trainee",
            name="trainer_ass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.Trainer",
            ),
        ),
    ]
