# Generated by Django 3.0.4 on 2020-04-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0004_auto_20200423_1416")]

    operations = [
        migrations.AddField(
            model_name="trainee",
            name="body_fat",
            field=models.IntegerField(default=1),
            preserve_default=False,
        )
    ]
