# Generated by Django 3.0.4 on 2020-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_trainee_body_fat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='current_weight',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='goal_weight',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
    ]
