# Generated by Django 3.0.4 on 2020-03-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user', '0005_auto_20200328_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer',
            field=models.BooleanField(default=True, verbose_name='trainer'),
        ),
        migrations.DeleteModel(
            name='people',
        ),
    ]
