# Generated by Django 3.0.4 on 2020-04-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("user", "0001_initial"), ("FitMeApp", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="person",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.Trainee",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="task_to_give",
            field=models.CharField(
                choices=[
                    ("beginner day 1", "beginner_day1"),
                    ("beginner day 2", "beginner_day2"),
                    ("beginner day 3", "beginner_day3"),
                    ("beginner day 4", "beginner day4"),
                    ("beginner day 5", "beginner day5"),
                    ("beginner day 6", "beginner day6"),
                    ("beginner day 7", "beginner day7"),
                    ("beginner day 8", "beginner day8"),
                    ("beginner day 9", "beginner day9"),
                    ("beginner day 10", "beginner day10"),
                ],
                max_length=50,
            ),
        ),
    ]
