# Generated by Django 3.0.4 on 2020-03-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitMeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='count_code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
