# Generated by Django 3.0.4 on 2020-03-27 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FitMeApp', '0002_auto_20200327_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='lname',
        ),
        migrations.AddField(
            model_name='trainee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
