# Generated by Django 3.0.4 on 2020-03-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitMeApp', '0003_auto_20200327_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='password',
        ),
        migrations.AddField(
            model_name='trainee',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitMeApp.TraineeAddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainee',
            name='trainee_phy',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitMeApp.TraineePhy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traineeaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='traineephy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
