# Generated by Django 3.0.4 on 2020-04-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("user", "0001_initial"), ("FitMeApp", "0003_auto_20200406_0630")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="person",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="user.Trainee",
            ),
        )
    ]
