# Generated by Django 3.0.4 on 2020-03-27 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FitMeApp', '0004_auto_20200327_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='trainee_phy',
        ),
        migrations.AddField(
            model_name='traineeaddress',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traineephy',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
