# Generated by Django 3.0.4 on 2020-03-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitMeApp', '0005_auto_20200327_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineeaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='traineephy',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trainee',
        ),
        migrations.DeleteModel(
            name='TraineeAddress',
        ),
        migrations.DeleteModel(
            name='TraineePhy',
        ),
    ]
